apiVersion: v1
kind: Pod
metadata:
  name: pi-haproxy
  namespace: default
  labels:
    role: pi-haproxy
spec:
  containers:
  - name: pi-haproxy
    image: mhurd/pi-haproxy:1.8.2
  nodeSelector:
    kubernetes.io/hostname: bresson
  restartPolicy: Always
