apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.1
        env:
          - name: POSTGRES_USER
            value: pi
          - name: POSTGRES_PASSWORD
            value: pi
          - name: POSTGRES_ADMIN_PASSWORD
            value: pi
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-nfs
          - mountPath: /mnt/common
            name: postgres-nfs-common
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 15
      volumes:
        - name: postgres-nfs
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-nfs-common
          persistentVolumeClaim:
            claimName: postgres-pvc-common
